/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pandemic;

import com.mycompany.pandemic.Controlador.Bd;
import com.mycompany.pandemic.Modelo.Ciudad;
import com.mycompany.pandemic.Modelo.Vacunas;
import com.mycompany.pandemic.Controlador.Partida;
import static com.mycompany.pandemic.MenuInicial.marcoAutores;
import com.mycompany.pandemic.Modelo.Enfermedad;
import com.mycompany.pandemic.Modelo.Tienda;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ruben
 */
public class PanelJugar extends javax.swing.JPanel {

   public static boolean marcoAcciones = false;
   public static boolean marcoTienda = false;
   public static boolean marcoProgreso = false;
   public static boolean marcoOpciones = false;
   public static boolean marcocura = false;
   public static boolean marcoinvestigar = false;
   
        public static Partida partida;
	public static ArrayList<Ciudad> ciudades = new ArrayList<Ciudad>();
	
	public static String colorCurar = "none";
   
    public PanelJugar() {
        initComponents();
        jButton5.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jLabel5.setVisible(false);
        jButton7.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel6.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jButton12.setVisible(false);
        jButton11.setVisible(false);
        jLabel14.setVisible(false);
        jButton13.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        jButton16.setVisible(false);
        jLabel15.setVisible(false);
        
        jButton17.setVisible(false);
        jButton10.setVisible(false);
        
        jButton18.setVisible(false);
        jButton19.setVisible(false);
        jButton20.setVisible(false);
        jButton21.setVisible(false);
        jLabel20.setVisible(false);
        
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jButton22.setVisible(false);
        
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        
        
            
        showCities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Chakra Petch Light", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ahora tienes: 10 puntos acumulados.");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel28.setFont(new java.awt.Font("Chakra Petch Light", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Has ganado: 10 puntos.");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_seguir.png")); // NOI18N
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_salirpart.png")); // NOI18N
        jButton11.setBorder(null);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_guardar.png")); // NOI18N
        jButton12.setBorder(null);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        jButton22.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_continuar.png")); // NOI18N
        jButton22.setBorder(null);
        jButton22.setContentAreaFilled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\ganado.png")); // NOI18N
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -160, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\perdido.png")); // NOI18N
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\pausa.png")); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -160, -1, -1));

        jLabel30.setFont(new java.awt.Font("Chakra Petch Light", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("<html><br>Bienvenido a Pandemic, intenta salvar al mundo.");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 380, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\consola.png")); // NOI18N
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 500, -1));

        jLabel23.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Error, no tienes suficiente dinero o tienes 4 acciones.");
        jLabel23.setToolTipText("");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, -1, -1));

        jLabel22.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Error, no tienes suficientes acciones o la vacuna esta investigada.");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 680, 950, -1));

        jLabel21.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("Error, no tienes suficientes acciones o la ciudad no se puede curar.");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, -1, -1));

        jLabel20.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Pulsa un color para curar la ciudad");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, -1, -1));

        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusazul.png")); // NOI18N
        jButton21.setBorder(null);
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, -1, -1));

        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusamarillo.png")); // NOI18N
        jButton20.setBorder(null);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, -1, -1));

        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusverde.png")); // NOI18N
        jButton19.setBorder(null);
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusrojo.png")); // NOI18N
        jButton18.setBorder(null);
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\panel_accion.png")); // NOI18N
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\panel_economia.png")); // NOI18N
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\aguja.png")); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\aguja.png")); // NOI18N
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\aguja.png")); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\aguja.png")); // NOI18N
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLabel15.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pulsa una ciudad para curar un punto de infección");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusamarillo.png")); // NOI18N
        jButton16.setBorder(null);
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusazul.png")); // NOI18N
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusverde.png")); // NOI18N
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_virusrojo.png")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, -1, -1));

        jLabel14.setFont(new java.awt.Font("Chakra Petch Light", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pulsa un color para investigar la vacuna");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 255));
        jLabel13.setText("90%");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("10%");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("20%");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("10%");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\prog_azul.png")); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 640, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\prog_amarillo.png")); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\prog_verde.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\prog_rojo.png")); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_tienda.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_atras.png")); // NOI18N
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 670, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_menu.png")); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_acciones.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_siguienteRonda.png")); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 670, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\button_progresos.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\panel_investigar.png")); // NOI18N
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\botones\\panel_curacion.png")); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 255));
        jLabel26.setText("Ronda numero: 0");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("100");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\mapa.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\paneles\\marcohoripng.png")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruben\\Desktop\\Pandemic\\src\\main\\java\\Assets\\logoeth.png")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_siguienteRonda2.png"));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_siguienteRonda.png"));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_acciones2.png"));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
         jButton1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_acciones.png"));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_tienda2.png"));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_tienda.png"));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_progresos2.png"));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_progresos.png"));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(marcoAcciones) {
            marcoAcciones = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            
    	} else if (marcoAcciones == false) {
            
            marcoAcciones = true;
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(true);
            jButton8.setVisible(true);
            jButton9.setVisible(true);
            
    	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        
        
        jLabel23.setVisible(false);
        
        if(marcoAcciones) {
            marcoAcciones = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(false);
            jButton8.setVisible(false);
            jButton9.setVisible(false); 
    	}
            marcoTienda = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(false); 
            jButton17.setVisible(false);
            jButton10.setVisible(false);

        if(marcoProgreso) {
            marcoProgreso = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(false); 
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
    	}
        
        if(marcoinvestigar) {
            marcoinvestigar = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
    	}
        
        if(marcocura) {
            marcocura = false;
            jLabel15.setVisible(false);
            
            jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel20.setVisible(false);
    	}
        
        showCities();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_atras2.png"));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_atras.png"));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Boton curacion
         if(marcocura) {
            marcocura = false;
            jLabel15.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
           
    	} else if (marcocura == false) {
            
            marcocura = true;
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
            
            
            jButton18.setVisible(true);
            jButton19.setVisible(true);
            jButton20.setVisible(true);
            jButton21.setVisible(true);
            jLabel20.setVisible(true);
            
    	}
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Boton inverstigar
        if(marcoinvestigar) {
            marcoinvestigar = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);

            
    	} else if (marcoinvestigar == false) {
            
            marcoinvestigar = true;
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
            jLabel14.setVisible(true);
            jButton13.setVisible(true);
            jButton14.setVisible(true);
            jButton15.setVisible(true);
            jButton16.setVisible(true);
            
            
    	}
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(marcoTienda) {
            marcoTienda = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(false);
            jButton17.setVisible(false);
            jButton10.setVisible(false);
            
    	} else if (marcoTienda == false) {
            
            marcoTienda = true;
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton17.setVisible(true);
            jButton10.setVisible(true);
            jButton5.setVisible(true);

            
    	}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(marcoProgreso) {
            marcoProgreso = false;
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            
    	} else if (marcoProgreso == false) {
            
            marcoProgreso = true;
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
    	}
        
        jLabel6.setText(Integer.toString(Vacunas.TodasVacunas.get(1).getPorcentajeVacuna()) + "%");
        jLabel11.setText(Integer.toString(Vacunas.TodasVacunas.get(2).getPorcentajeVacuna()) + "%");
        jLabel12.setText(Integer.toString(Vacunas.TodasVacunas.get(3).getPorcentajeVacuna()) + "%");
        jLabel13.setText(Integer.toString(Vacunas.TodasVacunas.get(0).getPorcentajeVacuna()) + "%");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

            marcoOpciones = true;
                        jLabel5.setVisible(true);
            jButton7.setVisible(true);
            jButton12.setVisible(true);
            jButton11.setVisible(true);
            jButton6.setVisible(false);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            jButton10.setVisible(false);
            jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jButton17.setVisible(false);
            jButton5.setVisible(false);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            marcoAcciones = false;
            
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            
            marcoProgreso = false;
            
    	
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        jButton7.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_seguir2.png"));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
       jButton7.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_seguir.png"));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            jLabel5.setVisible(false);
            jButton7.setVisible(false);
            jButton12.setVisible(false);
            jButton11.setVisible(false);
            jButton6.setVisible(true);
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            jButton10.setVisible(false);
            jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jButton17.setVisible(false);
            jButton5.setVisible(false);
            
            marcoOpciones = true;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        jButton11.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_salirpart2.png"));
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        jButton11.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_salirpart.png"));
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        JFrame marco = (JFrame)SwingUtilities.getWindowAncestor(this);
			marco.remove(this);
			marco.add(new MenuInicial());
			marco.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        jButton12.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_guardar2.png"));
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        jButton12.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\botones\\button_guardar.png"));
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //Aqui va guardar
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
            marcocura = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
            jButton8.setVisible(true);
            jButton9.setVisible(true);
    	
        
        if(Vacunas.investigarVacunaColor(1)){
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
        } else {
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel22.setVisible(true);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                if(marcoinvestigar) {
            marcoinvestigar = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
            jButton8.setVisible(true);
            jButton9.setVisible(true);
            
    	}
                
        if(Vacunas.investigarVacunaColor(2)){
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
        } else {
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel22.setVisible(true);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
 
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(marcoinvestigar) {
            marcoinvestigar = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
            jButton8.setVisible(true);
            jButton9.setVisible(true);
            
    	}

        if(Vacunas.investigarVacunaColor(3)){
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
        } else {
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            jLabel22.setVisible(true);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
            
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(marcoinvestigar) {
            marcoinvestigar = false;
            jLabel14.setVisible(false);
            jButton13.setVisible(false);
            jButton14.setVisible(false);
            jButton15.setVisible(false);
            jButton16.setVisible(false);
            
            jButton8.setVisible(true);
            jButton9.setVisible(true);
            
    	}
        if(Vacunas.investigarVacunaColor(0)){
            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
        } else {
            System.out.println("com.mycompany.pandemic.PanelJugar.jButton14ActionPerformed()");
            jLabel22.setVisible(true);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
            
        }
        

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Pasar ronda
        
        if(!partida.haPerdido() && !partida.haGanado()) {
            
				//background.removeAll();
				System.out.println("Ahora estamos en el turno " + Partida.turno.getNumTurno());
                                jLabel26.setText("Ronda numero: "+ Partida.turno.getNumTurno());
				Partida.turno.infectarCiudadesTurno();
				Partida.turno.pasarTurno();
				partida.tienda.sumardineroturno();
				
                                showCities();
                                showConsole();
			} else if(partida.haGanado()) {
				
				System.err.println("Ha ganado ya!");
                                
                                jLabel25.setVisible(true);
                                jButton22.setVisible(true);
                                
                                jLabel27.setVisible(true);
                                jLabel27.setText("Has ganado " + partida.getPuntos() + " puntos.");
                                
                                jLabel28.setVisible(true);
                                jLabel27.setText("Ahora tienes " + partida.puntos + " acumulados.");
                                
                                jButton2.setVisible(false);
                                jButton1.setVisible(false);
                                jButton4.setVisible(false);
                                jButton3.setVisible(false);
                                jButton6.setVisible(false);
                                
                                
				
			} else {
				
				System.err.println("Ha perdido ya!");
                                
                                 jLabel24.setVisible(true);
                                 jButton22.setVisible(true);
                                 
                                jLabel27.setVisible(true);
                                System.out.println(Partida.getPlayerPoints());
                                jLabel27.setText("Ahora tienes " + (Partida.getPlayerPoints() + partida.getPuntos()) + " acumulados.");
                                Bd.sumarPuntos(partida.jugador_username, partida.getPuntos());
                                
                                jLabel28.setVisible(true);
                                jLabel28.setText("Has ganado " + partida.puntos + " puntos.");
                                
                                jButton2.setVisible(false);
                                jButton1.setVisible(false);
                                jButton4.setVisible(false);
                                jButton3.setVisible(false);
                                jButton6.setVisible(false);
                                 
			}
        
        jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
        jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
        jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
        jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
        
        jLabel2.setText(Integer.toString(partida.tienda.getDinero()));
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Boton economia tienda
        if(marcoTienda) {
            marcoTienda = false;
            jButton5.setVisible(true); 
            jButton17.setVisible(true);
            jButton10.setVisible(true);
    	}
        if(partida.tienda.sumareconomia()){
            jLabel2.setText(Integer.toString(partida.tienda.getDinero()));
        } else {
            jButton10.setVisible(false);
            jButton17.setVisible(false);
            jLabel23.setVisible(true);
            marcoTienda = true;
        }
        
                
                
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // boton acciones tienda
        
        if(marcoTienda) {
            marcoTienda = false;
            jButton5.setVisible(true); 
            jButton17.setVisible(true);
            jButton10.setVisible(true);
    	}
        if(partida.tienda.sumaraccion()){
            jLabel2.setText(Integer.toString(partida.tienda.getDinero()));

            if(Partida.turno.getPuntosTotales() == 0){
                jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            } else if(Partida.turno.getPuntosTotales() == 1){
                jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            } else if(Partida.turno.getPuntosTotales() == 2){
                jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            } else if(Partida.turno.getPuntosTotales() == 3){
                jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
            } else if(Partida.turno.getPuntosTotales() == 4){
                jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
                jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja.png"));
            }
        } else {
            jButton10.setVisible(false);
            jButton17.setVisible(false);
            jLabel23.setVisible(true);
            marcoTienda = true;
        }             
                    
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // Boton curar rojo
        jLabel15.setVisible(true);
        marcocura = false;
        jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel20.setVisible(false);
            
            colorCurar = "Rojo";
            curarCiudad();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // Boton curar verde
        jLabel15.setVisible(true);
        marcocura = false;
        jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel20.setVisible(false);
            
            colorCurar = "Verde";
            curarCiudad();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // Boton curar amarillo
        jLabel15.setVisible(true);
        marcocura = false;
        jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel20.setVisible(false);
            
            colorCurar = "Amarillo";
            curarCiudad();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // Boton curar azul
        jLabel15.setVisible(true);
        marcocura = false;
        jButton18.setVisible(false);
            jButton19.setVisible(false);
            jButton20.setVisible(false);
            jButton21.setVisible(false);
            jLabel20.setVisible(false);
            colorCurar = "Azul";
            curarCiudad();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // Continuar
        JFrame marco = (JFrame)SwingUtilities.getWindowAncestor(this);
			marco.remove(this);
			marco.add(new MenuInicial());
			marco.setVisible(true);
        
    }//GEN-LAST:event_jButton22ActionPerformed
  
    public void curarCiudad(){
            jLabel1.removeAll();
            jLabel1.setVisible(false);
            for (Ciudad ciudad : ciudades) {
                    JButton botonCiudad = new JButton(ciudad.getNombreCiudad());
                    botonCiudad.setForeground(Color.black);
                    
                    botonCiudad.setBounds(ciudad.getCoordenadaX(), ciudad.getCoordenadaY(), 100, 20);
                    botonCiudad.setName(ciudad.getNombreCiudad());
                    botonCiudad.addActionListener((e) -> {
                        for (Ciudad ciudad2 : ciudades) {
			if(ciudad2.getNombreCiudad().equals(botonCiudad.getName())) {
				System.out.println(ciudad2.getNombreCiudad());
				ArrayList<Enfermedad> enfermedadList = ciudad2.getEnfermedadList();
				for (Enfermedad enfermedad : enfermedadList) {
					if(enfermedad.getColor().equals(colorCurar)) {
						if(Partida.turno.curar(enfermedad, colorCurar)) {
                                                    jLabel15.setVisible(false);
                                                        jButton8.setVisible(true);
                                                        jButton9.setVisible(true);
                                                        
                                                        if(Partida.turno.getPuntosTotales() == 0){
                                                            jLabel16.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                        } else if(Partida.turno.getPuntosTotales() == 1){
                                                            jLabel17.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                        } else if(Partida.turno.getPuntosTotales() == 2){
                                                            jLabel18.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                        } else if(Partida.turno.getPuntosTotales() == 3){
                                                            jLabel19.setIcon(new javax.swing.ImageIcon("src\\main\\java\\Assets\\aguja2.png"));
                                                        }
                                                        
							System.out.println("Ciudad curada con exito");
						}else{
                                                    
                                                    jLabel21.setVisible(true);
                                                    jLabel15.setVisible(false);
                                                }
					}
				}
				
				
				jLabel1.removeAll();
				jLabel1.setVisible(false);
				
			    for (Ciudad ciudad3 : ciudades) {
		        	JLabel label = new JLabel(ciudad3.getNombreCiudad());
		        	label.setForeground(Color.white);
                                label.setBounds(ciudad3.getCoordenadaX(), ciudad3.getCoordenadaY(), 100, 20);
                                int posXEnfermedad = -10;

		            for (Enfermedad enfermedad : ciudad3.getEnfermedadList()) {
			        	if(enfermedad.getNivelInfeccion() > 0) {
			        		posXEnfermedad = posXEnfermedad + 10;
			        		JLabel labelInfect = new JLabel(Integer.toString(enfermedad.getNivelInfeccion()));
			        		
				        	if(enfermedad.getColor().equals("Amarillo")) {
				        		labelInfect.setForeground(Color.yellow);
				        	} else if(enfermedad.getColor().equals("Rojo")) {
				        		labelInfect.setForeground(Color.red);
				        	} else if(enfermedad.getColor().equals("Azul")) {
				        		labelInfect.setForeground(Color.blue);
				        	} else if(enfermedad.getColor().equals("Verde")) {
				        		labelInfect.setForeground(Color.green);
				        	}
				        	
				        	labelInfect.setBounds(ciudad3.getCoordenadaX() + posXEnfermedad, ciudad3.getCoordenadaY() + 15, 100, 20);
				        	
				        	
				 
				            jLabel1.add(labelInfect);
			        	}
		            }
		            jLabel1.add(label);
				}
				
				ciudad2.setEnfermedadList(enfermedadList);
			}
			jLabel1.setVisible(true);
		}
                        
                    });
	            int posXEnfermedad = -10;
	            
	            for (Enfermedad enfermedad : ciudad.getEnfermedadList()) {
		        	if(enfermedad.getNivelInfeccion() > 0) {
		        		posXEnfermedad = posXEnfermedad + 10;
		        		JLabel labelInfect = new JLabel(Integer.toString(enfermedad.getNivelInfeccion()));
		        		
			        	if(enfermedad.getColor().equals("Amarillo")) {
			        		labelInfect.setForeground(Color.yellow);
			        	} else if(enfermedad.getColor().equals("Rojo")) {
			        		labelInfect.setForeground(Color.red);
			        	} else if(enfermedad.getColor().equals("Azul")) {
			        		labelInfect.setForeground(Color.blue);
			        	} else if(enfermedad.getColor().equals("Verde")) {
			        		labelInfect.setForeground(Color.green);
			        	}
			        	
			        	labelInfect.setBounds(ciudad.getCoordenadaX() + posXEnfermedad, ciudad.getCoordenadaY() + 15, 100, 20);

			            jLabel1.add(labelInfect);
		        	}
	            }
	            
	            jLabel1.add(botonCiudad);
                }
	        
	        jLabel1.setVisible(true);
    }
    
    public void showCities(){
        jLabel1.setVisible(false); 
        jLabel1.removeAll();
                        for (Ciudad ciudad : ciudades) {
                                int posXEnfermedad = -10;
                                JLabel label = new JLabel(ciudad.getNombreCiudad());
                                label.setForeground(Color.white);
                                label.setBounds(ciudad.getCoordenadaX(), ciudad.getCoordenadaY(), 100, 20);
                                
                                for (Enfermedad enfermedad : ciudad.getEnfermedadList()) {
                                            posXEnfermedad = posXEnfermedad + 10;
                                            if(enfermedad.getNivelInfeccion() > 0) {
                                                    JLabel labelInfect = new JLabel(Integer.toString(enfermedad.getNivelInfeccion()));

                                                switch (enfermedad.getColor()) {
                                                    case "Amarillo":
                                                        labelInfect.setForeground(Color.yellow);
                                                        break;
                                                    case "Rojo":
                                                        labelInfect.setForeground(Color.red);
                                                        break;
                                                    case "Azul":
                                                        labelInfect.setForeground(Color.blue);
                                                        break;
                                                    case "Verde":
                                                        labelInfect.setForeground(Color.green);
                                                        break;
                                                    default:
                                                        break;
                                                }

                                                    labelInfect.setBounds(ciudad.getCoordenadaX()+ posXEnfermedad, ciudad.getCoordenadaY() + 15, 100, 20);

                                                    jLabel1.add(labelInfect);
                                            }


                                            }

                                        jLabel1.add(label);
                                    }
		        jLabel1.setVisible(true);
    }
    
    public void showConsole(){
        String consola = "";
        System.out.println(partida.getConsoleLog());
        consola += "<html>";
        
        for (String input : partida.getConsoleLog()){
            consola += input + " <br>";
        }
        
        consola += "</html>";
        System.out.println(consola);
        jLabel30.setText("<html> " + consola + " <br></html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
